const cabinet=[
 ["👨🏻‍💼","James Mercer","Chancellor",64],["👩🏽‍⚕️","Aisha Rahman","Health",79],["👩🏼‍💼","Eleanor Price","Home",58],["👨🏿‍💼","Marcus Cole","Foreign",72],["👩🏻‍💼","Sophie Grant","Education",83]
];
const regions=["Scotland","North","Midlands","Wales","London","South East"];
const $=s=>document.querySelector(s); const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));
let state={},currentEvent=null,locked=false,currentBriefing=null,consulted=new Set();

const PROMISES=[["nhs","🏥","Cut NHS waiting lists"],["housing","🏠","Build more homes"],["growth","📈","Grow the economy"],["tax","💷","Keep taxes down"],["crime","🚔","Cut crime"],["climate","⚡","Secure clean energy"]];
const ISSUE_GOALS={nhs_strike:"End the disruption without losing control of the public finances.",planning:"Get more homes built while keeping enough MPs to pass the law.",tax_gap:"Close the fiscal gap without wrecking your promises or public services.",rates:"Help households without pretending you control the Bank of England.",prisons:"Keep the justice system functioning when there is almost no spare capacity.",energy:"Protect households now without locking in an unaffordable response.",migration:"Reduce the backlog through a system that is lawful and administratively workable.",defence:"Protect national security while managing cost and escalation risk.",lords:"Get your legislation through two Houses of Parliament.",election:"Turn five years of governing into enough constituency wins to stay in office.",eastern_europe_crisis:"Respond to a war you did not choose without losing control of risk, alliances or spending.",shipping_shock:"Absorb a global shock that is raising British prices even though it started abroad."};
const POWER_MAPS={
 nhs_strike:[["YOU","Set negotiating mandate","you"],["→","","arrow"],["NHS / UNIONS","Must agree a settlement",""]],
 planning:[["YOU + CABINET","Propose reform","you"],["→","","arrow"],["PARLIAMENT","Must pass the law",""] ,["→","","arrow"],["COUNCILS","Implement much of it",""]],
 rates:[["YOU","Tax & spending policy","you"],["≠","","arrow"],["BANK OF ENGLAND","Sets Bank Rate","blocked"]],
 lords:[["COMMONS","Your majority matters","you"],["→","","arrow"],["LORDS","Can amend & delay",""]],
 migration:[["YOU","Set policy & resources","you"],["→","","arrow"],["HOME OFFICE","Must administer it",""] ,["↔","","arrow"],["COURTS","Can review legality","blocked"]],
 defence:[["YOU","Set UK position","you"],["↔","","arrow"],["ALLIES","Coordinate response",""]],
 eastern_europe_crisis:[["YOU","UK support & diplomacy","you"],["↔","","arrow"],["ALLIES","Shared response",""] ,["≠","","arrow"],["WAR","Not under your control","blocked"]],
 shipping_shock:[["YOU","Cushion domestic impact","you"],["≠","","arrow"],["GLOBAL TRADE","Prices & routes","blocked"]],
 default:[["YOU + CABINET","Choose direction","you"],["→","","arrow"],["PARLIAMENT / STATE","Authorise & deliver",""] ,["→","","arrow"],["OUTCOME","People & markets react",""]]
};

function freshState(){return{turn:0,approval:52,economy:61,britain:48,power:73,majority:24,treasury:55,housing:45,promises:[],customPromises:[],delayed:[],regions:{Scotland:48,North:51,Midlands:52,Wales:50,London:55,"South East":52},eventIndex:0,decisions:0,newsIndex:0,externalSeen:{},archive:[]};}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelector(id)?.classList.add('active');}
function totalPromises(){return state.promises.length+state.customPromises.length;}
function renderPromises(){const grid=$('#promiseGrid');if(!grid)return;grid.innerHTML='';PROMISES.forEach(([id,icon,label])=>{const b=document.createElement('button');b.className='promise'+(state.promises.includes(id)?' selected':'');b.innerHTML=`<b>${icon} ${label}</b><span class="muted">Voters will remember this</span>`;b.onclick=()=>{const i=state.promises.indexOf(id);if(i>=0)state.promises.splice(i,1);else if(totalPromises()<3)state.promises.push(id);renderPromises();};grid.appendChild(b);});state.customPromises.forEach((label,i)=>{const b=document.createElement('button');b.className='promise selected';b.innerHTML=`<b>✍️ ${label}</b><span class="muted">Custom promise</span>`;b.onclick=()=>{state.customPromises.splice(i,1);renderPromises();};grid.appendChild(b);});if($('#promiseCount'))$('#promiseCount').textContent=totalPromises();if($('#startBtn')){$('#startBtn').disabled=totalPromises()!==3;$('#startBtn').textContent=totalPromises()===3?'Lock in manifesto →':`Choose ${3-totalPromises()} more`;}}

function pickEvent(){if(state.eventIndex>=4&&!state.externalSeen.europe){state.externalSeen.europe=true;return EXTERNAL_EVENTS[0];}if(state.eventIndex>=11&&!state.externalSeen.shipping){state.externalSeen.shipping=true;return EXTERNAL_EVENTS[1];}const e=BASE_EVENTS[state.eventIndex]||BASE_EVENTS[BASE_EVENTS.length-1];state.eventIndex++;return e;}
function totalPlayable(){return BASE_EVENTS.length+EXTERNAL_EVENTS.length;}
function updateUI(){
 state.approval=clamp(state.approval);state.economy=clamp(state.economy);state.britain=clamp(state.britain);state.power=clamp(state.power);state.treasury=clamp(state.treasury);
 const monthsElapsed=Math.min(60,Math.round((state.decisions/totalPlayable())*60)),left=Math.max(0,60-monthsElapsed);
 if($('#turnText'))$('#turnText').textContent=`Month ${Math.min(60,monthsElapsed+1)} of 60`;
 if($('#electionCountdown'))$('#electionCountdown').textContent=left===1?'1 month':`${left} months`;
 if($('#termProgressBar'))$('#termProgressBar').style.width=(monthsElapsed/60*100)+'%';
 if($('#approvalVal'))$('#approvalVal').textContent=Math.round(state.approval)+'%';if($('#majorityVal'))$('#majorityVal').textContent=state.majority;if($('#treasurySide'))$('#treasurySide').textContent=Math.round(state.treasury);
 if($('#economyVal'))$('#economyVal').textContent=Math.round(state.economy);if($('#britainVal'))$('#britainVal').textContent=Math.round(state.britain);if($('#powerVal'))$('#powerVal').textContent=Math.round(state.power);
 if($('#decisionCount'))$('#decisionCount').textContent=state.decisions;renderArchive();
}
function rotateNews(){if(!WORLD_NEWS?.length)return;$('#tickerText').textContent=WORLD_NEWS[state.newsIndex%WORLD_NEWS.length].replace(/^[A-Z ]+ • /,'');state.newsIndex++;}
function switchStage(id){document.querySelectorAll('.case-stage').forEach(s=>s.classList.remove('active'));document.getElementById(id)?.classList.add('active');window.scrollTo({top:Math.max(0,$('#eventCard').offsetTop-60),behavior:'smooth'});}
function loadEvent(){
 locked=false;consulted=new Set();currentEvent=pickEvent();currentBriefing=getBriefing(currentEvent);$('#outcomeFlow').classList.add('hidden');$('#eventCard').classList.remove('hidden');switchStage('stageSituation');
 $('#eventIcon').textContent=currentEvent.icon;$('#eventCategory').textContent=currentEvent.category.toUpperCase();$('#eventTitle').textContent=currentEvent.title;$('#eventText').textContent=currentEvent.text;$('#caseNumber').textContent=String(state.decisions+1).padStart(2,'0');$('#issueGoal').textContent=ISSUE_GOALS[currentEvent.id]||'Make a workable decision and understand what happens next.';
 $('#systemExplainer').textContent=currentBriefing.explainer;$('#controlText').textContent=currentBriefing.control;renderPowerMap();renderAdvisers();renderChoices();
 const involvesTreasury=currentEvent.choices.some(c=>c.e&&Object.prototype.hasOwnProperty.call(c.e,'treasury'));$('#treasuryPill').classList.toggle('hidden',!involvesTreasury);
 if(currentEvent.category.toLowerCase().includes('international')||currentEvent.category.toLowerCase().includes('global'))toast('EXTERNAL SHOCK • This was not in your manifesto. You still own the response.');
 rotateNews();updateUI();window.scrollTo({top:0,behavior:'smooth'});
}
function renderPowerMap(){const path=POWER_MAPS[currentEvent.id]||POWER_MAPS.default;$('#powerMap').innerHTML=path.map(([name,desc,type])=>type==='arrow'?`<div class="power-arrow">${name}</div>`:`<div class="power-node ${type}"><small>${desc}</small><b>${name}</b></div>`).join('');}
function adviserData(){
 const primary={icon:currentEvent.avatar||'🧑‍💼',name:currentEvent.adviser||'Lead minister',role:'Owns the policy problem',advice:currentEvent.adviserText||'There is no cost-free option.'};
 const treasuryChoice=[...currentEvent.choices].sort((a,b)=>(b.e?.treasury||0)-(a.e?.treasury||0))[0];
 const treasury={icon:'💷',name:'The Treasury',role:'Optimises fiscal resilience',advice:treasuryChoice?`The safest option for the public finances is “${treasuryChoice.t}”. That does not mean it is the best political or service outcome.`:'We need to understand the recurring cost before committing.'};
 const whipChoice=[...currentEvent.choices].sort((a,b)=>((b.e?.power||0)+(b.e?.approval||0))-((a.e?.power||0)+(a.e?.approval||0)))[0];
 const whip={icon:'🏛️',name:'Chief Whip',role:'Optimises votes and party unity',advice:whipChoice?`Your MPs are most comfortable with “${whipChoice.t}”. They are thinking about their seats as much as the national policy.`:'I need to know whether our MPs will actually vote for this.'};
 return [primary,treasury,whip].filter((a,i,arr)=>arr.findIndex(x=>x.name===a.name)===i).slice(0,3);
}
function renderAdvisers(){const advisers=adviserData();$('#adviserChoices').innerHTML=advisers.map((a,i)=>`<button class="adviser-card" data-adviser="${i}"><div class="adviser-face">${a.icon}</div><div><b>${a.name}</b><small>${a.role}</small><div class="adviser-answer hidden">${a.advice}</div></div><span class="ask">ASK</span></button>`).join('');$('#adviceCount').textContent='0';$('#adviceNextBtn').disabled=true;document.querySelectorAll('.adviser-card').forEach(b=>b.onclick=()=>consultAdviser(b,advisers[+b.dataset.adviser]));}
function consultAdviser(button,a){const id=button.dataset.adviser;if(consulted.has(id))return;if(consulted.size>=2)return;consulted.add(id);button.classList.add('selected');button.querySelector('.adviser-answer').classList.remove('hidden');button.querySelector('.ask').textContent='HEARD';$('#adviceCount').textContent=consulted.size;$('#adviceNextBtn').disabled=consulted.size<2;if(consulted.size>=2)document.querySelectorAll('.adviser-card:not(.selected)').forEach(x=>x.disabled=true);}
function choiceFacts(c,i){const e=c.e||{},facts=[];if(e.treasury!==undefined){const cost=e.treasury<=-6?'High cost':e.treasury<=-3?'Medium cost':e.treasury<0?'Low cost':e.treasury>=3?'Raises headroom':'Low fiscal effect';facts.push([cost,e.treasury<0?'cost':'support']);}if((e.power||0)<=-2)facts.push(['MP resistance likely','risk']);else if((e.power||0)>=2)facts.push(['Easier with your party','support']);if((e.britain||0)>=3)facts.push(['Service upside','support']);if((e.britain||0)<=-3)facts.push(['Delivery risk','risk']);facts.push(['Public reaction: forecast','unknown']);return facts.slice(0,4);}
function renderChoices(){const box=$('#choices');box.innerHTML='';currentEvent.choices.forEach((c,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<div class="choice-title">${c.t}</div><div class="choice-sub">${c.s}</div><div class="choice-facts">${choiceFacts(c,i).map(([t,k])=>`<span class="fact-chip ${k}">${t}</span>`).join('')}</div>`;b.onclick=()=>choose(c,i);box.appendChild(b);});}
function applyEffects(e){const shown=[];const labels={approval:['Public mood','%'],economy:['Economy',''],britain:['Services',''],power:['Political authority',''],treasury:['Treasury room',''],housing:['Housing delivery','']};Object.entries(e||{}).forEach(([k,v])=>{if(state[k]===undefined)state[k]=50;state[k]+=v;if(labels[k])shown.push([labels[k][0],v]);});return shown;}
function stakeholderReactions(c){const e=c.e||{},people=currentBriefing.stakeholders||[];const score=(e.approval||0)+(e.britain||0),treasury=e.treasury||0,power=e.power||0;const vals=[score,treasury,power];return people.slice(0,3).map((s,i)=>{const v=vals[i]??0;return[s[0],v>1?'Welcomes the direction':v<-1?'Pushes back':'Waits to see the detail',v>1?'positive':v<-1?'negative':'neutral'];});}
function mediaStories(c){const fiscal=c.e?.treasury||0,service=c.e?.britain||0;return[
 ['THE DAILY HERALD',c.h||`PM CHOOSES ${c.t.toUpperCase()}`,c.d||'Downing Street faces the political consequences.'],
 ['THE CHRONICLE',service>1?`${c.t.toUpperCase()}: GOVERNMENT SAYS RESULTS WILL FOLLOW`:`MINISTERS DEFEND ${c.t.toUpperCase()}`,'A more neutral reading of what the government actually announced.'],
 ['MARKET & POLICY WIRE',fiscal<=-3?'NEW COMMITMENT ADDS PRESSURE TO PUBLIC FINANCES':fiscal>=3?'DECISION IMPROVES FISCAL HEADROOM':'LIMITED IMMEDIATE FISCAL EFFECT','Institutions and markets focus on different incentives from political newspapers.']
 ];}
function choose(c,index){if(locked)return;locked=true;state.decisions++;const effects=applyEffects(c.e);if(c.delay)state.delayed.push({due:state.decisions+c.delay.after,source:currentEvent.title,choice:c.t,...c.delay});const reactions=stakeholderReactions(c);state.archive.unshift({issue:currentEvent.title,choice:c.t,month:Math.max(1,Math.round((state.decisions/totalPlayable())*60)),headline:c.h});
 $('#eventCard').classList.add('hidden');$('#outcomeFlow').classList.remove('hidden');document.querySelectorAll('.outcome-step').forEach(x=>x.classList.remove('active'));$('#outcomeReaction').classList.add('active');$('#feedbackTitle').textContent=c.t;$('#feedbackText').textContent='You have made the call. Different groups interpret the same decision through their own incentives.';$('#groupReactions').innerHTML=reactions.map(([g,r,k])=>`<div class="reaction ${k}"><b>${g}</b><span>${r}</span></div>`).join('');$('#effects').innerHTML=effects.map(([label,v])=>`<div class="effect-v3"><small>${label}</small><b>${v>0?'+':''}${v}</b></div>`).join('')||'<div class="effect-v3"><small>Immediate measurable effect</small><b>Limited</b></div>';$('#mediaFrames').innerHTML=mediaStories(c).map(([source,h,d])=>`<div class="media-frame"><small>${source}</small><b>${h}</b><p>${d}</p></div>`).join('');updateUI();window.scrollTo({top:Math.max(0,$('#outcomeFlow').offsetTop-60),behavior:'smooth'});}
function processDelayed(){const due=state.delayed.filter(x=>x.due<=state.decisions);state.delayed=state.delayed.filter(x=>x.due>state.decisions);if(due.length){due.forEach(x=>{applyEffects(x.e);state.archive.unshift({issue:`Callback: ${x.source}`,choice:x.text,month:Math.max(1,Math.round((state.decisions/totalPlayable())*60)),callback:true});});const x=due[0];toast(`CALLBACK • Remember “${x.choice}” on ${x.source}? ${x.text}`);}}
function continueGame(){processDelayed();if(currentEvent.final){finishGame();return;}loadEvent();}
function renderArchive(){if(!$('#archiveList'))return;$('#archiveCount').textContent=`${state.archive.length} ${state.archive.length===1?'entry':'entries'}`;$('#archiveList').innerHTML=state.archive.slice(0,10).map(a=>`<div class="archive-item"><b>${a.callback?'⏳ ':''}${a.issue}</b><span>Month ${a.month} • ${a.choice}</span></div>`).join('')||'<div class="archive-item"><span>Your decisions will appear here.</span></div>';}
function promiseScore(){let n=0;state.promises.forEach(p=>{if(p==='nhs'&&state.britain>=55)n++;if(p==='housing'&&state.housing>=52)n++;if(p==='growth'&&state.economy>=65)n++;if(p==='tax'&&state.treasury>=52)n++;if(p==='crime'&&state.britain>=55)n++;if(p==='climate'&&state.economy>=60&&state.britain>=55)n++;});return n;}
function finishGame(){show('#endScreen');const avg=(state.approval+state.economy+state.britain+state.power)/4,seats=Math.max(220,Math.min(390,Math.round(260+state.approval*1.15+state.power*.35+(state.economy-50)*.45))),won=seats>=326,delivered=promiseScore();let legacy=state.britain>=65&&state.economy>=60?'THE REFORMER':state.treasury>=65?'THE BOOKKEEPER':state.power>=70?'THE SURVIVOR':won?'THE OPERATOR':'THE ONE-TERM PM';$('#grade').textContent=legacy;$('#endTitle').textContent=won?'The country gives you another go.':'Your time in Downing Street is over.';$('#endSummary').textContent=`You finish on ${seats} projected seats and delivered ${delivered}/${totalPromises()} manifesto promises. Economy ${Math.round(state.economy)}, services ${Math.round(state.britain)}, Treasury ${Math.round(state.treasury)}. ${won?'You survived the trade-offs.':'The trade-offs caught up with you.'}`;$('#scoreGrid').innerHTML=[["Seats",seats],["Public",Math.round(state.approval)+'%'],['Economy',Math.round(state.economy)],['Services',Math.round(state.britain)]].map(([a,b])=>`<div class="score"><small>${a}</small><b>${b}</b></div>`).join('');}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),6000);}
function save(){} function clearSave(){}
state=freshState();renderPromises();
